pr по 3-ему дипломному заданию
87stels87/Diplom_3 pull request #1
Opened 2022-06-02 17:48 UTC by 87stels87

2022-06-07 13:24 UTC, pavel-ulan requested changes
Это задание тоже стоит поправить (проверку разделов, имена методов и т.д.)

2022-06-07 13:24 UTC, pavel-ulan commented on src/main/java/MainPage.java
> +        filling.scrollTo().shouldBe().isDisplayed();
Я тебя растрою, но filling у тебя всегда будут Displayed, даже если не доскролишь туда =)
Так что тесты с проверкой разделов надо переделать.
Попробуй проскролить разделы и смотреть как меняются имена классов в верстке у разделов. И построй проверку "в каком разделе я нахожусь" на этой основе.

2022-06-07 13:24 UTC, pavel-ulan commented on src/test/java/TransfersTest.java
> +        objRegistrationPage.clickLogoOnRegistrationPage();
А может оберни все эти шаги в один? будет как-то лаконичнее что ли.

2022-06-07 13:24 UTC, pavel-ulan commented on src/test/java/RegistrationTest.java
> +        objRegistrationPage.getMessageNotCorrectPassword();
У тебя почти все тесты похожи просто на какой-то список действий. И если не знать, что в последнем шаге у тебя проверки, складывается ощущение, что у тебя их нет.
Что бы такого не было, или называй метод "проверкачего-то" или используй ожидания в тесте, а не в методах.

2022-06-08 20:07 UTC, 87stels87 commented on src/test/java/TransfersTest.java
> +        objRegistrationPage.clickLogoOnRegistrationPage();
сделал

2022-06-11 06:48 UTC, 87stels87 commented on src/test/java/RegistrationTest.java
> +        objRegistrationPage.getMessageNotCorrectPassword();
переименовал методы заключительный в тестах. Добавил в название check. Не хочется селенидовские проверки на слой бизнес логики выводить.

2022-06-11 11:45 UTC, 87stels87 commented on src/main/java/MainPage.java
> +        filling.scrollTo().shouldBe().isDisplayed();
готово. теперь тесты эти смотрят на текущий раздел. Для главной страницы по умолчанию раздел с булками текущий

2022-06-11 20:18 UTC, pavel-ulan commented on src/test/java/RegistrationTest.java
> +        objRegistrationPage.getMessageNotCorrectPassword();
Иногда это оправдано, иногда нет. По этой причине и решений может быть несколько. =)

2022-06-11 20:20 UTC, pavel-ulan approved these changes
Гут 👍

2024-01-15 10:39 UTC, merged